# Configure this Discovery Server
eureka:
  server:
      enableSelfPreservation: true
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false

server:
  port: 1111
  
spring:
  thymeleaf:
    enabled: false